### ISSUE TITLE
Unable to run uefi-run, reports error: No space left on device

### ISSUE THREAD

**Issue by xaionaro** [Richard-W/uefi-run#11]
```
xaionaro@void:~/fbcode/privatecore/firmware/efitools/secstatus$ uefi-run -b /home/xaionaro/firmware/OVMF.fd -q $(which kvm) ./build/RELEASE_GCC5/X64/secstatus.efi
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "No space left on device" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

```
xaionaro@void:~/fbcode/privatecore/firmware/efitools/secstatus$ uefi-run ./build/RELEASE_GCC5/X64/secstatus.efi
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "No space left on device" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by xaionaro** [comment]
Never mind. I needed to add `-m 128`.
